### ISSUE TITLE
hesiod test fail

### ISSUE THREAD

**Issue by harihare** [achernya/hesiod#7]
hi, 
/root/hesiod/hesiod/src/lib/.libs
 ./lt-hestest ./../hestest.conf 

Line 10 failed in hesiod_getmailhost.
The below line is the 10th line in hestest.conf. Is there any change in the pop / mail server on MIT. 
getmailhost systest POP:PO10.MIT.EDU:systest

Test is failing here.

**Comment by harihare** [comment]
@achernya 
@ebroder 
Can you please help me here.

**Comment by achernya** [comment]
Ugh, this test depends on MIT infrastructure. It should be updated to EXCHANGE.MIT.EDU

User systest, Type EXCHANGE, Box: EXCHANGE.MIT.EDU (systest@EXCHANGE.MIT.EDU)

**Comment by harihare** [comment]
getmailhost systest Box:EXCHANGE.MIT.EDU:systest

I tried with above input, still it failed with same error. 
@achernya

**Comment by achernya** [comment]
Fixed in fc0e1d7db42fa931f80982c6d3326375b7e3b266.

**Comment by harihare** [comment]
It worked, Thanks
